### ISSUE TITLE
Handygccs 

### ISSUE THREAD

**Issue by jeanboyx3** [jlobue10/ALLY_Nobara_fixes#2]
how where you able to get handygccs on nabora? i have the steam deck edition but i keep getting errors, could it be because i'm using kde with konsole commands?

**Comment by jlobue10** [comment]
So you will need to run `python -m pip install build wheel installer` (and maybe the same command with `sudo`) and then run the `build.sh` script. You will then likely need to fix the `systemd` service call for `handycon` by either symlinking the proper binary or fixing the service call directly to fix the `handycon` path. Nobara installs ` handycon` to `/usr/local/bin` but the service call expects it in `/usr/bin`.

**Comment by jeanboyx3** [comment]
sweet! that fixed it. Thanks a ton, hopefully the developers of hancygccs can get the back buttons working in the future.

**Comment by jlobue10** [comment]
I think they are aware of this.

**Comment by jeanboyx3** [comment]
so i'm trying to replicate this again after reinstalling nobara due to upgrading my ssd. but i cant for the life of me get the service to work. i replicated what i did, but once i sudo systemctl enable --now handycon it doesnt seem to want to do anything in regards to power or side buttons working.

**Comment by jlobue10** [comment]
Oh do I have great news for you... GE just added HandyGCCS yesterday. Open the updater app and search for it. Install it from there, and you should be good to go.

**Comment by jlobue10** [comment]
BIOS 330 and 331 seem to have broken the front buttons with HandyGCCS. I think forks are available that address this if it's not already fixed in the main HandyGCCS branch. We recently found a way for steam-patch to be more reliable, so a lot of us in the Discord have switched back to that for front button and menu control.

**Comment by jlobue10** [comment]
At this point, I'd just go away from using HandyGCCS on the ALLY in general as rogue-enemy has surpassed it in usefulness and functionality. Closing this issue.
